/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryCreateNestedManyWithoutUsersInput } from "./CategoryCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TransactionsCreateNestedManyWithoutUsersInput } from "./TransactionsCreateNestedManyWithoutUsersInput";
import { WalletCreateNestedManyWithoutUsersInput } from "./WalletCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CategoryCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CategoryCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  categories?: CategoryCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => TransactionsCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TransactionsCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TransactionsCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  transactionsItems?: TransactionsCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => WalletCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WalletCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WalletCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  wallets?: WalletCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
