/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TransactionsService } from "../transactions.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TransactionsCreateInput } from "./TransactionsCreateInput";
import { Transactions } from "./Transactions";
import { TransactionsFindManyArgs } from "./TransactionsFindManyArgs";
import { TransactionsWhereUniqueInput } from "./TransactionsWhereUniqueInput";
import { TransactionsUpdateInput } from "./TransactionsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TransactionsControllerBase {
  constructor(
    protected readonly service: TransactionsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Transactions })
  @nestAccessControl.UseRoles({
    resource: "Transactions",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTransactions(
    @common.Body() data: TransactionsCreateInput
  ): Promise<Transactions> {
    return await this.service.createTransactions({
      data: {
        ...data,

        categoryId: {
          connect: data.categoryId,
        },

        userId: data.userId
          ? {
              connect: data.userId,
            }
          : undefined,

        walletId: {
          connect: data.walletId,
        },
      },
      select: {
        amount: true,

        categoryId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        description: true,
        id: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },

        walletId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Transactions] })
  @ApiNestedQuery(TransactionsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Transactions",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async transactionsItems(
    @common.Req() request: Request
  ): Promise<Transactions[]> {
    const args = plainToClass(TransactionsFindManyArgs, request.query);
    return this.service.transactionsItems({
      ...args,
      select: {
        amount: true,

        categoryId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        description: true,
        id: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },

        walletId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Transactions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Transactions",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async transactions(
    @common.Param() params: TransactionsWhereUniqueInput
  ): Promise<Transactions | null> {
    const result = await this.service.transactions({
      where: params,
      select: {
        amount: true,

        categoryId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        description: true,
        id: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },

        walletId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Transactions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Transactions",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTransactions(
    @common.Param() params: TransactionsWhereUniqueInput,
    @common.Body() data: TransactionsUpdateInput
  ): Promise<Transactions | null> {
    try {
      return await this.service.updateTransactions({
        where: params,
        data: {
          ...data,

          categoryId: {
            connect: data.categoryId,
          },

          userId: data.userId
            ? {
                connect: data.userId,
              }
            : undefined,

          walletId: {
            connect: data.walletId,
          },
        },
        select: {
          amount: true,

          categoryId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          date: true,
          description: true,
          id: true,
          updatedAt: true,

          userId: {
            select: {
              id: true,
            },
          },

          walletId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Transactions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Transactions",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTransactions(
    @common.Param() params: TransactionsWhereUniqueInput
  ): Promise<Transactions | null> {
    try {
      return await this.service.deleteTransactions({
        where: params,
        select: {
          amount: true,

          categoryId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          date: true,
          description: true,
          id: true,
          updatedAt: true,

          userId: {
            select: {
              id: true,
            },
          },

          walletId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
